
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'snowflake_experimental'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models", "0_models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  snowflake_experimental:
    staging:
      +materialized: view
      schema: "{{ env_var('DBT_TRGT_SCHEMA') }}"
      database: "{% if target.name == 'prod' %} SA_MKN_SANDBOX {% else %} SA_MKN_SANDBOX {% endif %}"
    marts:
      +materialized: table
      schema: "{{ env_var('DBT_TRGT_SCHEMA') }}"
      database: "{% if target.name == 'prod' %} SA_MKN_SANDBOX_SILVER {% else %} SA_MKN_SANDBOX {% endif %}"
    metrics:
      +materialized: table
      schema: "{{ env_var('DBT_TRGT_SCHEMA') }}"
      database: "{% if target.name == 'prod' %} SA_MKN_SANDBOX_GOLD {% else %} SA_MKN_SANDBOX {% endif %}"
