models:
  - name: final_customers
    config:
      constraints:
        primary_key: PK

    columns:
      - name: PK
        data_type: INTEGER
        description: Primary key of the customer
        data_tests:
          - not_null
      - name: updated_at
        data_tests:
          - not_null