version: 2

models:
  - name: stg_jaffle_shop__orders
    data_tests:
      - dbt_utils.expression_is_true:
          expression: "order_total - tax_paid = subtotal"

    columns:
      - name: order_id
        data_tests:
          - not_null
          - unique

      - name: subtotal
        data_tests:
          - is_positive_value
