version: 2

models:
  - name: stg_jaffle_shop__orders
    description: "This model cleans up order data."
    data_tests:
      - dbt_utils.expression_is_true:
          expression: "order_total - tax_paid = subtotal"

    columns:
      - name: order_id
        description: "Primary key for orders."
        data_tests:
          - not_null
          - unique
      - name: subtotal
        data_tests:
          - is_positive_value

  - name: stg_jaffle_shop__order_items
    columns:
      - name: order_id
        data_tests:
          - relationships:
              field: order_id
              to: ref('stg_jaffle_shop__orders')