version: 2

sources:
  - name: jaffle_shop
    database: DWH
    schema: jaffle_shop
    tables:
      - name: customers
      - name: items
      - name: orders
      - name: products
      - name: stores
      - name: supplies