version: 2

sources:
  - name: jaffle_shop
    database: DWH
    schema: jaffle_shop
    description: "my e-commerce data"
    freshness: 
      error_after:
        count: 2
        period: day
      warn_after:
        count: 1
        period: day
    tables:
      - name: customers
      - name: items
      - name: orders
      - name: products
      - name: stores
      - name: supplies