version: 2

sources:
  - name: jaffle_shop
    database: DWH
    schema: jaffle_shop
    description: "my e-commerce data"
    tables:
      - name: customers
      - name: items
      - name: orders
        loaded_at_field: ORDERED_AT
        freshness: 
          error_after:
            count: 5000
            period: day
          warn_after:
            count: 1
            period: day
      - name: products
      - name: stores
      - name: supplies